### ISSUE TITLE
No image in demo

### ISSUE THREAD

**Issue by vintserg** [bfortuner/labelml#1]
Hi,
I tried the demo on the site and from the repository,
But the processing screen is empty and does not contain a picture.

Tell me how to fix this
Thank you!

**Comment by bfortuner** [comment]
Sorry I turned off the EC2 instance to save money, but you can still download and run locally!

**Comment by elyas20** [comment]
Hi, 

can you give more details on how to use local data ?

**Comment by RahulBhalley** [comment]
There is no button to import an image. How can I label an image then?
